import React from 'react';



function Shop() {
    return (
        <div>
            <h1>WELCOME TO BBC NEWS </h1>
            <p>BBC News is an operational business division of the British Broadcasting Corporation (BBC) responsible for the gathering and broadcasting of news and current affairs. The department is the world's largest broadcast news organisation and generates about 120 hours of radio and television output each day, as well as online news coverage. The service maintains 50 foreign news bureaux with more than 250 correspondents around the world. Fran Unsworth has been Director of News and Current Affairs since January 2018. <br />
            The department's annual budget is in excess of £350 million; it has 3,500 staff, 2,000 of whom are journalists. BBC News' domestic, global and online news divisions are housed within the largest live newsroom in Europe, in Broadcasting House in central London. Parliamentary coverage is produced and broadcast from studios in Millbank in London. Through the BBC English Regions, the BBC also has regional centres across England and national news centres in Northern Ireland, Scotland and Wales. All nations and English regions produce their own local news programmes and other current affairs and sport programmes. <br />The BBC is a quasi-autonomous corporation authorised by Royal Charter, making it operationally independent of the government, who have no power to appoint or dismiss its director-general, and required to report impartially. However, as with all major media outlets, it has been accused of political bias from across the political spectrum, both within the UK and abroad.</p>
            <p>BBC News is an operational business division of the British Broadcasting Corporation (BBC) responsible for the gathering and broadcasting of news and current affairs. The department is the world's largest broadcast news organisation and generates about 120 hours of radio and television output each day, as well as online news coverage. The service maintains 50 foreign news bureaux with more than 250 correspondents around the world. Fran Unsworth has been Director of News and Current Affairs since January 2018. <br />
            The department's annual budget is in excess of £350 million; it has 3,500 staff, 2,000 of whom are journalists. BBC News' domestic, global and online news divisions are housed within the largest live newsroom in Europe, in Broadcasting House in central London. Parliamentary coverage is produced and broadcast from studios in Millbank in London. Through the BBC English Regions, the BBC also has regional centres across England and national news centres in Northern Ireland, Scotland and Wales. All nations and English regions produce their own local news programmes and other current affairs and sport programmes. <br />The BBC is a quasi-autonomous corporation authorised by Royal Charter, making it operationally independent of the government, who have no power to appoint or dismiss its director-general, and required to report impartially. However, as with all major media outlets, it has been accused of political bias from across the political spectrum, both within the UK and abroad.</p><p>BBC News is an operational business division of the British Broadcasting Corporation (BBC) responsible for the gathering and broadcasting of news and current affairs. The department is the world's largest broadcast news organisation and generates about 120 hours of radio and television output each day, as well as online news coverage. The service maintains 50 foreign news bureaux with more than 250 correspondents around the world. Fran Unsworth has been Director of News and Current Affairs since January 2018. <br />
            The department's annual budget is in excess of £350 million; it has 3,500 staff, 2,000 of whom are journalists. BBC News' domestic, global and online news divisions are housed within the largest live newsroom in Europe, in Broadcasting House in central London. Parliamentary coverage is produced and broadcast from studios in Millbank in London. Through the BBC English Regions, the BBC also has regional centres across England and national news centres in Northern Ireland, Scotland and Wales. All nations and English regions produce their own local news programmes and other current affairs and sport programmes. <br />The BBC is a quasi-autonomous corporation authorised by Royal Charter, making it operationally independent of the government, who have no power to appoint or dismiss its director-general, and required to report impartially. However, as with all major media outlets, it has been accused of political bias from across the political spectrum, both within the UK and abroad.</p>
        </div>
    );
}

export default Shop;